from types import TracebackType
from typing import Any, Optional, Type, TypeVar, overload

import numpy as np
from numpy.typing import DTypeLike, NDArray

_Region = TypeVar("_Region", bound="SharedRegion")

class SharedRegion:
    def __init__(self, handle: Any) -> None: ...
    @classmethod
    def create(cls: Type[_Region], name: str, capacity: int) -> _Region: ...
    @classmethod
    def open(cls: Type[_Region], name: str) -> _Region: ...
    def as_buffer(self) -> memoryview: ...
    @overload
    def as_numpy(self, dtype: None = ...) -> NDArray[np.uint8]: ...
    @overload
    def as_numpy(self, dtype: DTypeLike) -> NDArray[Any]: ...
    def notify(self) -> None: ...
    def wait(self, timeout_ms: int = ...) -> bool: ...
    async def wait_async(self, timeout_ms: int = ...) -> bool: ...
    def try_wait(self) -> bool: ...
    def close(self) -> None: ...
    def __enter__(self: _Region) -> _Region: ...
    def __exit__(
        self,
        exc_type: Optional[Type[BaseException]],
        exc_value: Optional[BaseException],
        traceback: Optional[TracebackType],
    ) -> None: ...
